items = [
    {
        'title': 'OMitra',
        'description': """Rama was the sole developer on OMitra Android App. India's first app for alleviating problems encountered in train travel. Advanced live train tracking,
        Wakup alarm, Train noticeboard, Important Railway contacts, Family trip tracking""",
        'thumbnail': 'omitra_thumb.png',
        'image': 'omitra.png',
        'client_name': 'OMitra on Google Play',
        'client_url': 'https://play.google.com/store/apps/details?id=com.train.omitraapp',
        'date': '2014-2015',
        'service': 'Android Development',
    },
    {
        'title': 'Flip Hound',
        'description': """Fliphound is an automated media buying platform for digital billboards. Fliphound allows a broad range of businesses to include digital billboards in their media mix. This mobile app allows users to switch out artwork, edit bids, change frequency, contact a team member and access an easy to read dashboard.""",
        'thumbnail': 'fliphound_thumb.png',
        'image': 'fliphound.png',
        'client_name': 'Flip Hound on App Store',
        'client_url': 'https://itunes.apple.com/us/app/fliphound/id951847683?',
        'date': '2014',
        'service': 'iOS Development',
    },
    {
        'title': 'Dres.sy',
        'description': 'Dres.sy is a virtual Fitting Room for your store. Manu lead the development of Dres.sy beta for Imaginate software. It has many cutting edge features like Computer Vision, Async Task execution, Color clustering and some elements of Augmented Reality',
        'thumbnail': 'dressy_thumb.png',
        'image': 'dressy.png',
        'client_name': 'Dres.sy',
        'client_url': 'http://www.dres.sy',
        'date': '2013',
        'service': 'Web Development',
    },
    {
        'title': 'Optmyzr',
        'description': 'Optmyzr is a collection of Google AdWords Tools for Advertisers, Consultants, and Agencies. Manu worked as Senior Software Engineer for Optmyzr where he was responsible for maintenance and new feature development in One Click Optimizations and Data Insights',
        'thumbnail': 'optmyzr_home_thumb.png',
        'image': 'optmyzr_home.png',
        'client_name': 'Optmyzr Inc',
        'client_url': 'http://www.optmyzr.com',
        'date': '2014-2015',
        'service': 'Web Development',
    },
    {
        'title': 'RISSTA',
        'description': """RISSTA – Railway Interactive Security Solution for Traveller’s Assistance.
        This App is developed in collaboration with Secunderabad and Hyderabad RPF.""",
        'thumbnail': 'rissta_thumb.png',
        'image': 'rissta.png',
        'client_name': 'RISSTA on Google Play',
        'client_url': 'https://play.google.com/store/apps/details?id=com.omitrasaftyapp',
        'date': '2015',
        'service': 'Android Development',
    },
    {
        'title': 'Your Rewards Zone',
        'description': """A friendly mobile application that allows you to save money, receive real time offers from nearby stores, keep track of your loyalty offers, and gift cards all in one place - even make dining reservations!""",
        'thumbnail': 'yourrewards_thumb.png',
        'image': 'yourrewards.png',
        'client_name': 'Your Rewards on App Store',
        'client_url': 'https://itunes.apple.com/us/app/yourrewardszone/id951011045?ls=1&mt=8',
        'date': '2014',
        'service': 'iOS Development',
    },

]
